all:
  children:
    app_servers:
      hosts:
        app_server:
          ansible_host: "{{ app_server_private_ip }}"
          ansible_user: ubuntu
          ansible_ssh_private_key_file: "{{ ssh_private_key_path }}"
          ansible_ssh_common_args: '-o ProxyCommand="ssh -W %h:%p -i {{ ssh_private_key_path }} ubuntu@{{ bastion_public_ip }}"'