---
vault_db_password: "StudyShare2024!"
vault_secret_key: "django-insecure-your-secret-key-here-change-in-production"
vault_aws_access_key_id: "REPLACE_WITH_KEY"
vault_aws_secret_access_key: "REPLACE_WITH_SECRET"