---
# Infrastructure variables from Terraform outputs
app_server_private_ip: "10.0.2.36"
bastion_public_ip: "98.80.211.118"
ssh_private_key_path: "../studyshare-key-2.pem"

# AWS configuration
aws_region: "us-east-1"
ecr_repository_url: "436119632580.dkr.ecr.us-east-1.amazonaws.com/studyshare-app"
app_version: "latest"

# Database configuration
db_host: "studyshare-db.c0v22u8o00d6.us-east-1.rds.amazonaws.com"
db_name: "studyshare"
db_user: "studyshare_user"
db_password: "{{ vault_db_password }}"

# Application secrets
SECRET_KEY: "{{ vault_secret_key }}"